#
# Module manifest for module 'PSApplicationInsights'
# Generated by: Jos Verlinde
# Generated on: 17-10-2016
#

@{
    # Script module associated with this manifest.
    RootModule = 'PSApplicationInsights'
    ModuleVersion = '0.10.0'

    # ID used to uniquely identify this module
    GUID = '1706beeb-bb2f-4a51-b1fd-f972e62f4d2d'

    # Author of this module
    Author = 'Jos Verlinde [MSFT], Michel Zehnder'
    CompanyName = 'Microsoft, Michel Zehnder'
    Copyright = '(c) 2016-2017 Jos Verlinde. All rights reserved.'
    Description = 'Add Application Insights to PowerShell to get both simple and advanced tracing to gain insight to how your scripts are actually working, including errors and functional usage'

    # AppInsights Module is dependent on .Net 4.5
    DotNetFrameworkVersion = '4.5'

    # not tested on anyting lower than 4.0
    PowerShellVersion = '4.0'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(  
        #Application Insights Dlls that are needed for the exposed functionality 
        #base AI Service 
        '..\packages\Microsoft.ApplicationInsights.2.8.1\lib\net45\Microsoft.ApplicationInsights.dll',
        #AI For fat clients 
        '..\packages\Microsoft.ApplicationInsights.WindowsServer.2.8.1\lib\net45\Microsoft.AI.WindowsServer.dll',
        '..\packages\Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.8.1\lib\net45\Microsoft.AI.ServerTelemetryChannel.dll', 
        #AI based on perfcounters 
        '..\packages\Microsoft.ApplicationInsights.PerfCounterCollector.2.8.1\lib\net45\Microsoft.AI.PerfCounterCollector.dll',
        # Tracking of dependencies 
        '..\packages\Microsoft.ApplicationInsights.DependencyCollector.2.8.1\lib\net45\Microsoft.AI.DependencyCollector.dll',
        '..\packages\Microsoft.ApplicationInsights.Agent.Intercept.2.4.0\lib\net45\Microsoft.AI.Agent.Intercept.dll',
		#Dependency
		'..\packages\System.Diagnostics.DiagnosticSource.4.5.1\lib\net45\System.Diagnostics.DiagnosticSource.dll',
		

        #And the additional powershell modules
        # Send Base event types 
        '.\public\AIEvent.psm1',
        '.\public\AITrace.psm1',
        '.\public\AIMetrics.psm1',
        # Exceptions and errors 
        '.\public\AIException.psm1',   
        # Waiting for dependencies                 
        '.\public\AIDependency.psm1',
        #perf Counter 
        '.\public\AIPerformanceCollector.psm1',
        #Live perf counters 
        '.\public\LiveMetrics.psm1',

    #   '.\AIOperation.psm1',
        '.\private\HelperFunctions.psm1'
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = '*'

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Tracing','ApplicationInsights','Monitoring','DevOps')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/PSApplicationInsights/PSApplicationInsights/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/PSApplicationInsights/PSApplicationInsights'
            # A URL to an icon representing this module.
            IconUri = 'https://github.com/PSApplicationInsights/PSApplicationInsights/raw/master/images/PSAI.png'

            # ReleaseNotes of this module
			ReleaseNotes = 'https://github.com/PSApplicationInsights/PSApplicationInsights/blob/master/CHANGELOG.md'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''



}

